[package]
name = "dump_main_route_table"
version = "0.1.0"
edition = "2021"

[dependencies]
netlink = { path = "../../", features = ["all"]}
bincode = "1.3.3"
serde = { version = "1.0.164", features = ["derive"] }