[package]
name = "netlink"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.26.2"
thiserror = "1.0.40"
bincode = "1.3.3"
serde = { version = "1.0.164", features = ["derive"] }
serde_repr = "0.1"
derive_builder = "0.12.0"
log = "0.4.19"